config/routes.rb
Rails.application.routes.draw do
    resources :students
end

app/models/student.rb
class Student < ActiveRecord::Base
  validates :name, :course, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController

  def index
    @students = Student.all
  end

  def show
    @student = Student.find(params[:id])
  end

  def new
    @student = Student.new
  end

  def create
    @student = Student.new(student_params)

    if @student.save
      redirect_to students_path
    else
      render :new
    end

  end

  def edit
    @student = Student.find(params[:id])
  end

  def update
    @student = Student.find(params[:id])

    if @student.update_attributes(student_params)
      redirect_to students_path
    else
      render :edit
    end
  end

  def destroy
    @student = Student.find(params[:id])
    @student.destroy
    redirect_to students_path
  end

  private

  def student_params
    params.require(:student).permit(:name, :course)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>StudentUnion</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/students/edit.html.erb
<h1>Make Changes Here</h1>

<%= form_for(@student) do |f| %>
  <div>
    <%= f.label('Student Name:') %>
    <%= f.text_field(:name) %>
  </div>
  <div>
    <%= f.label('Course Name:') %>
    <%= f.text_field(:course) %>
  </div>
  <div>
    <%= f.submit('Save Changes') %>
  </div>

<% end %>

<p><%= link_to('Cancel', students_path) %></p>

app/views/students/index.html.erb
<h1>Home Page</h1>

<%= link_to('Sign Up for Course', new_student_path) %>

<ul>
  <% @students.each do |student| %>
  <li>
    <%= link_to(student.name, student_path(student.id)) %>
    <%= student.course %>
  </li>
  <% end %>
</ul>

app/views/students/new.html.erb
<h1>Sign Up for Course</h1>

<%= form_for(@student) do |f| %>
  <div>
    <%= f.label('Student Name:') %>
    <%= f.text_field(:name) %>
  </div>
  <div>
    <%= f.label('Course Name:') %>
    <%= f.text_field(:course) %>
  </div>
  <div>
    <%= f.submit('Submit') %>
  </div>

<% end %>

<p><%= link_to('Cancel', students_path) %></p>

app/views/students/show.html.erb
<h1><%= @student.name %></h1>
<h3><%= @student.course %></h3>

<p><%= link_to('Edit', edit_student_path) %></p>
<p><%= link_to('Delete Record', @student, method: :delete, data: {confirm: 'Are you sure?'}) %></p>
<p><%= link_to('Back to Home Page', students_path) %></p>